name: Build

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
      COVERALLS_REPO_TOKEN: ${{ secrets.github_token }}
    strategy:
      fail-fast: false
      matrix:
        target: ["run_spec", "run2_spec"]
    steps:
    - uses: actions/checkout@v2
    - name: Install Coveralls reporter
      run: |
        printenv | sort
        curl -L https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-linux.tar.gz | tar zxv
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.1
        bundler-cache: true
    - name: Run tests
      run: |
        bundle exec rspec spec/${{ matrix.target }}.rb
    - name: Coveralls upload
      run: |
        ./coveralls -p --job-flag=${{ matrix.target }} --debug
  finalize:
    needs: test
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
      COVERALLS_REPO_TOKEN: ${{ secrets.github_token }}
    steps:
    - name: Install Coveralls reporter
      run: |
        curl -L https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-linux.tar.gz | tar zxv
    - name: Finilize Coveralls build
      run: |
        ./coveralls -d --debug
